#!/usr/bin/env bash
set -xe
ssh khanh@100.69.15.9 << EOF
    set -xe
    /opt/homebrew/bin/tmux has-session -t example_app 2> /dev/null && /opt/homebrew/bin/tmux kill-session -t example_app
    rm -rf /tmp/example_app
EOF

ssh khanh@100.93.62.117 << EOF
    set -xe
    /usr/bin/tmux has-session -t example_app 2> /dev/null && /usr/bin/tmux kill-session -t example_app
    rm -rf /tmp/example_app
EOF

